services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_NAME: tennis
      DB_USER: tennis_user
      DB_PASSWORD: tennis_pass
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: tennis
      POSTGRES_USER: tennis_user
      POSTGRES_PASSWORD: tennis_pass
